[pytest]
addopts = --import-mode=importlib
pythonpath =
    packages/environments/mock-gcal
    packages/environments/mock-gdoc
    packages/environments/mock-gdrive
    packages/environments/mock-gmail
    packages/environments/mock-slack
testpaths =
    tests
    example_tasks
    packages/environments/mock-gcal/tests
    packages/environments/mock-gdoc/tests
    packages/environments/mock-gdrive/tests
    packages/environments/mock-gmail/tests
    packages/environments/mock-slack/tests
norecursedirs =
    .data
    .local
    .pytest_cache
    .venv
    __pycache__
    build
    dist
